# Generated by Django 6.0.2 on 2026-03-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="qr_token",
            field=models.CharField(
                blank=True, editable=False, max_length=36, null=True, unique=True
            ),
        ),
    ]
