# Generated by Django 6.0.2 on 2026-03-10 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cliente_qr_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={"ordering": ["orden_pos", "nombre"]},
        ),
        migrations.AddField(
            model_name="producto",
            name="color_pos",
            field=models.CharField(blank=True, default="#0a8f08", max_length=20),
        ),
        migrations.AddField(
            model_name="producto",
            name="controlar_stock",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
        migrations.AddField(
            model_name="producto",
            name="mostrar_en_pos",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="orden_pos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="core.categoriaproducto",
            ),
        ),
    ]
