# Generated by Django 6.0.2 on 2026-03-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_categoriaproducto_alter_producto_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionSitio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_negocio",
                    models.CharField(default="Mi Negocio", max_length=120),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="configuracion/"
                    ),
                ),
                ("color_primario", models.CharField(default="#0d6efd", max_length=7)),
                ("color_secundario", models.CharField(default="#6c757d", max_length=7)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración del sitio",
                "verbose_name_plural": "Configuración del sitio",
            },
        ),
    ]
