# Generated by Django 6.0.2 on 2026-03-13 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_configuracionsitio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Casillero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(unique=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "qr_token",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                ("asignado_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente_actual",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="casillero_actual",
                        to="core.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Casillero",
                "verbose_name_plural": "Casilleros",
                "ordering": ["numero"],
            },
        ),
    ]
