# Generated by Django 6.0.2 on 2026-03-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_casillero"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventaitem",
            name="es_cortesia",
            field=models.BooleanField(default=False),
        ),
    ]
