# Generated by Django 6.0.2 on 2026-03-16 14:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_ventaitem_es_cortesia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venta",
            options={"ordering": ["-creada_en"]},
        ),
        migrations.AddField(
            model_name="casillero",
            name="nombre_ocupante",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="venta",
            name="casillero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventas",
                to="core.casillero",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="descuento_manual",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="nombre_cliente_libre",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to="core.cliente",
            ),
        ),
    ]
