# Generated by Django 6.0.2 on 2026-03-16 17:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_venta_descuento_porcentaje"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventaitem",
            name="descuento_porcentaje",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
    ]
